### PR TITLE
#65 no-redirect should disable the follow redirect

### PR DESCRIPTION
**Pull request by npeters**

### CODE REVIEW

**Comment by quangson91** [comment]
@npeters Thank you for the contribution.
Could you please resolve the conflict?

Have a nice week :)

**Comment by quangson91** [comment]
@all-contributors please add @npeters for  code

**Comment by npeters** [comment]
The github action work well now !  Thank you @quangson91

**Comment by karian7** [comment]
@quangson91 

Hi.

The '@no-redirect' setting of [this binary](https://github.com/restcli/restcli/releases/download/v1.7.4/restcli.zip) does not work(also homebrew). Please check if there are any mistakes when packaging.

**Pull request merged**
